name: lint


on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.3
        java-version: '19'
        distribution: 'oracle'

    - name: Install dependencies
      run: |
        pip install poetry
        poetry install

    - name: Lint with Black
      run: |
        poetry run black --check .

    